---
title: "Which is the best country to live in?"
author: "Kirill Tumanov, Mattia Storero, Lucas Stark"
date: "14 12 2019"
output: 
  html_document:
    number_sections: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, include = F)
### Data 
library(OECD) #connection to OECD database
library(eurostat) #connection to eurostat database
library(wbstats) #connection 1 to world bank
library(WDI) #connection 2 or world bank
library(Quandl) #connection to Quandl
library(gapminder) #data from gapminder
### Cleaning and Visualizing
library(rvest) #if we need to harvest data from webpages
library(ggmap) #this way we can visualize data on maps (-> world map)
library(tidyverse) #basic cleaning/ organising functions
```

# Background



# Research Question


# Data Sources
```{r import}
### 1 OECD ###
#- load table with all available variables
OECDdatasets <- get_datasets()
avg_unemployment <- get_dataset("AVD_DUR")

### 2 EUROSTAT ###
#- load table with all available variables
ES_datasets <- search_eurostat("")
#df <- get_eurostat()

### 3 WORLD BANK ###
#- load table with all available variables
WDI_datasets <- as_tibble(WDIcache()$series)
temp <- stringr::str_detect(WDI_datasets[["name"]], "net enrolment")
temp2 <- WDI_datasets[temp,]
#temp2[["description"]]
#load datasets:
WDI_ch_mor <- WDI(indicator = "SH.DYN.MORT.Q3")
WDI_ED_pri <- WDI(indicator = "UIS.NERT.1") # % in primary education
WDI_ED_sec <- WDI(indicator = "UIS.NERA.3") # % in upper secondary education

### 4 Quandl ###
#- a way to search for datasets:
Q_datasets <- Quandl.search("time in.* education")
# load datasets:
# df <- Quandl(code)
Q_lifeExp <- Quandl("22254767")
Q_x2 <- Quandl("")

### 5 Gapminder ###
#- 6 variables: country, continent, year, lifeExp, pop, gdpPercap
summary(gapminder)


```

# Data Cleaning
```{r cleaning}

```

# Data Analysis
```{r analysis}

```

## Economic Variables

## Health Variables

## Other Variables

# Conclussion


